### ISSUE TITLE
Implement multithreading

### ISSUE THREAD

**Issue by jeremystucki** [SirRade/JNF_NEAT#51] opened 2016-09-23 08:51 UTC
It is quite important to gain performance on multi-core systems.

![image](https://cloud.githubusercontent.com/assets/7629727/18779937/7a6859fc-817b-11e6-856a-8bb1cb8da83f.png)

**Comment by janhohenheim** [comment] 2016-09-24 13:26
Closed as duplicate of #5

**Closed as completed by janhohenheim** 2016-09-24 13:26 UTC
Labels: bug
